### PR TITLE
add definition

### PR DESCRIPTION
**Pull request by taoqf**
Just in case someone who won't use [vscode-nls-dev](https://github.com/Microsoft/vscode-nls-dev)

### CODE REVIEW

**Comment by taoqf** [comment]
Will this pr be merged?

**Comment by dbaeumer** [comment]
Sorry I somehow never saw this. Can you explain the PR a little

**Comment by taoqf** [comment]
This was an easier way I didn't bundle the localized files.

**Comment by dbaeumer** [comment]
If you don't want to bundle anything then you can still use nls.localize and not rewrite the calls (e.g. running `nls-dev`). Everything will still work and the messages are in the language you put them into the source code.

**Comment by dbaeumer** [comment]
Please ping if I misunderstood something.

**Pull request closed without merging**
