### PR TITLE
Fix: allow library to gracefully bundle when imported

### PR DESCRIPTION
**Pull request by tomrav**
My team is using the `vscode-css-languageserver` in a browser environment alongside `monaco` and other vscode tooling.
When attempting to bundle the project the process fails as `vscode-nls` attempts to import `fs` which is not available.

We've picked the same solution as used by [typescript](https://github.com/microsoft/TypeScript/blob/v3.8.3/package.json#L122) and verified it actually bundles without errors.

### CODE REVIEW

**Comment by tomrav** [comment]
@dbaeumer would appreciate it if you can review this, we could use this fix downstream.

**Comment by dbaeumer** [comment]
@tomrav can you please explain what that fix does. I am not very familiar with bundling for the browser.

**Comment by dbaeumer** [comment]
I am asking because without any fs support / shim the module will not function.

**Comment by AviVahl** [comment]
Heya there. Tom and I are working together.

We, at [stylable](https://github.com/wix/stylable), import `vscode-css-languageservice`, which imports and uses `vscode-nls`.

We are trying to bundle and use our abstraction inside the browser (together with `monaco-editor`). When bundling, `webpack` follows the imports and gets to `vscode-nls`, which is a Node library and imports Node APIs.

The thing is, `vscode-css-languageservice` doesn't really use the Node-specific parts (the ones that make use of `fs`).

All its usages are:
```
import * as nls from 'vscode-nls';
const localize = nls.loadMessageBundle();  
```
It doesn't pass an argument, which means `loadMessageBundle` falls back to the default `localize` function.

The "browser" field, as [defined here](https://github.com/defunctzombie/package-browser-field-spec), is supported by bundlers out there. `webpack`, which we use, amongst them.

By setting `fs` to `false`, `webpack` will bundle `vscode-nls` successfully giving it _an empty object_ instead of an actual `fs` API. Functions that don't use it (e.g. the default `localize`) still work. 

With that field in place, `webpack` is able to bundle our project without errors coming in about `vscode-nls` importing `fs`, and we are able to see everything working successfully in the browser.

TypeScript uses a similar approach to allow their `lib/typescripts.js` to work both in Node and in the browser (when bundled).

I hope this clears the intent of this PR.

**Comment by dbaeumer** [comment]
But this is luck right now. If `vscode-css-languageservice` changes its code to pass something to `loadMessageBundle` then the `vscode-nls` library will fail. And there is no way to fix it.

The difference with TS is that they have an abstraction layer that allows clients to plugin its own fs system making TS actually work in the browser in all cases. 

This being said the right approach is to also add this abstraction layer to `vscode-nls` and then add the `browser` setting.

Would you be willing to work on this?

**Comment by AviVahl** [comment]
Well, as an initial step to get things working in all cases, I would also add `const readFileSync = fs?.readFileSync;` at top level, and change the first `if` expression in `loadMessageBundle` to say: 
```ts
if (!file || !readFileSync) {
```
That would ensure lib falls back to default localize function when `fs` is empty.

I've pinged @tomrav to get access to his fork, so I can add that change.

Thinking forward, this library could offer providing a custom host, like `typescript` does. Perhaps via the `config` function fields. I could add that as well, but I would rather do it in a separate PR.

**Comment by AviVahl** [comment]
@dbaeumer made it fallback when `file` is passed. wdyt? viable approach?

**Comment by AviVahl** [comment]
It should be noted that this will also fix vscode's need to ship [a mock](https://github.com/microsoft/vscode/blob/master/src/vs/nls.mock.ts) when they publish `monaco-editor/-core` packages with esm dist.

FYI @alexdima

**Comment by dbaeumer** [comment]
I looked into this in more detail in the node LSP repository and the right approach is to split the code into three parts:

- common containing the code that run in both browser and node
- browser specific code
- node specific code

We can then use the browser field in package.json to point to a different entry point for the browser. A good article describing this approach is: https://nolanlawson.com/2017/01/09/how-to-write-a-javascript-package-for-both-node-and-the-browser/

Any interest on working on that an approach?

**Comment by AviVahl** [comment]
done. :) I ensured same types/exports are coming out from both entry points.

**Comment by AviVahl** [comment]
added a sanity test for entrypoints.

**Comment by dbaeumer** [comment]
@AviVahl thanks for doing this. I quickly look at this look exactly what I had in mind. Will do a review beginning of next week. Need to finish things today.

**Comment by tomrav** [comment]
@dbaeumer I imagine you're fairly busy as is, but we'd appreciate it if you'd get a chance to review this. Thanks!

**Comment by dbaeumer** [comment]
@tomrav I will try to get to it this week. Sorry about this but I first need to finish other things :-)

**Comment by AviVahl** [comment]
Thanks for the review. :+1: 

I have several observations/questions:
- The example repository you've linked to shows _several_ npm packages (each folder has a separate `package.json` as well).
- It makes sense to use project references for that case, where each package has a separate `./dist`.
- Using that setup for `vscode-nls` feels **way** over engineered. Other than the types separation, there's a lot more infra without any runtime gain.
- Where should the output of each folder (`common/node/browser`) be directed to? should I use a `tsconfig.base.json`? should that specify the `outDir` as `./lib`? 
- What path should `node` and `browser` import? `../common/common`? how would that work when built (into a single folder)?

**Comment by AviVahl** [comment]
Scratch that. Done.

TBH, I was a bit afraid of project references. I played with it in the past and it was buggy and under-documented. Seemed to work fine with ts@3.9 (at least for this simple setup).

**Comment by dbaeumer** [comment]
@AviVahl thanks. Actually project references work quite well for me since TS 3.8.x

This week is endgame week for VS Code. I will merge the PR and create a new version beginning of next week when endgame is done. Feel free to ping to ensure I will not forget :-)

**Comment by AviVahl** [comment]
hey @dbaeumer. thanks for merging this.

could you clarify the status of the next release of `vscode-nls`? I've noticed the last two commits to master (after this PR) broke CI again.

**Comment by dbaeumer** [comment]
@AviVahl GREAT. Ping me mid next week. I usually let a next version be out there for some time before shipping a new version.

**Comment by AviVahl** [comment]
@dbaeumer ping :smiley:

**Comment by tomrav** [comment]
Decided to give this release a check locally and opened a new PR for a bug found - see #29

**Comment by dbaeumer** [comment]
See my comments in #29

**Pull request merged**
